spring:
  profiles:
    active:
    - dev
---
server:
  port: 8001

spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://localhost:3306/db8001?zeroDateTimeBehavior=convertToNull&characterEncoding=UTF-8&useSSL=false
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: root
  application:
    name: dept-provider


mybatis:
  configuration:
    map-underscore-to-camel-case: true


eureka:
  client:
    service-url:
        #defaultZone: http://localhost:7001/eureka
        defaultZone: http://eureka7001.com:7001/eureka/
  instance:
    instance-id: dept-provider
    prefer-ip-address: true #访问路径可以显示IP地址

info:
  app.name: springcloud
  company.name: www.ajacom.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$
---
server:
  port: 8001

spring:
  profiles: test
  datasource:
    url: jdbc:mysql://localhost:3306/db8003?zeroDateTimeBehavior=convertToNull&characterEncoding=UTF-8&useSSL=false
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: root
  application:
    name: dept-provider


mybatis:
  configuration:
    map-underscore-to-camel-case: true


eureka:
  client:
    service-url:
        #defaultZone: http://localhost:7001/eureka
        defaultZone: http://eureka7001.com:7001/eureka/
  instance:
    instance-id: dept-provider
    prefer-ip-address: true #访问路径可以显示IP地址

info:
  app.name: springcloud
  company.name: www.ajacom.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$